plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.displayguardian'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.displayguardian"
        minSdk 21
        targetSdk 30
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
